name: clock
version: 1.0.0-dev
description: A fakeable wrapper for dart:core clock APIs
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/clock

environment:
  sdk: '>=1.24.0 <2.0.0'
